import networkx as nx

from .basic_block import basic_block
from .label import label
from .statements import statement
from .to_statement import to_statement
from ChironAST import ChironAST

def _get_leaders(ir: list[tuple[ChironAST.Instruction, int]]) -> list[int]:
    '''
    Identify the indices in the IR where basic blocks start. A basic block
    starts at the first instruction, after a control flow instruction (like
    a jump or branch), or at the destination of a control flow instruction.

    :param list[ChironAST.Instruction] ir: The list of IR instructions to
        analyse.
    :return list[int]: A sorted list of indices where basic blocks start.
    '''

    boundaries = [0]  # The first instruction is always the start of a basic block

    for i, instr in enumerate(ir):
        if instr[1] != 1:
            # If the instruction is a jump/branch, add the target as a boundary
            boundaries.append(i + instr[1])

            # Add the next instruction as a boundary
            boundaries.append(i + 1)

            # NOTE: If the instruction is a jump/branch but its target is the
            # next instruction, the instruction is redundant and should be
            # removed at BB-level analysis, so we don't need to add the target
            # as a boundary in that case.
            #
            # If the instruction is an unconditional jump, the next instruction
            # may be unreachable. While we can detect this at BB-level analysis,
            # we use the next BB's start to find the current BB's end. Instead,
            # we will remove unreachable blocks at CFG-level analysis.

        elif isinstance(instr[0], (ChironAST.PenCommand, ChironAST.MoveCommand, ChironAST.GotoCommand)):
            # These are syscalls, which also cause control flow changes, so we
            # treat them as jumps (which is what they'll become later).
            boundaries.append(i + 1)

    return sorted(set(boundaries))

def _get_ssa_bbs(ir: list[tuple[ChironAST.Instruction, int]]) \
    -> list[tuple[label, dict[str, basic_block]]]:
    '''
    Create basic blocks from the IR based on the identified boundaries.

    :param list[tuple[ChironAST.Instruction, int]] ir:
        The list of IR instructions to convert to basic blocks.
    :return list[tuple[label, dict[str, basic_block]]]:
        A list of basic blocks created from the IR.
    '''

    # Locate basic block boundaries in the IR
    basic_block_boundaries = _get_leaders(ir)
    basic_block_boundaries.append(len(ir))  # Add the end of the IR as a boundary
    # Note that the past-the-end address may have been generated by _get_leaders()
    # if it was the target of a jump (the target being the end of the program).
    # Appending in this case causes a duplicate entry, which is alright: the
    # past-the-end address then falls into an empty basic block.

    version: dict[str, int] = {}            # Mapping of variable names to their current SSA version numbers

    # BB-wise list of variables that are live at the end of the BB along with
    # their versions, used to determine sources for phi-function insertion.
    #
    # All variables are actually assumed alive at the end of the BB; the key
    # information here is to find the last assigned index for each variable in the
    # BB, which will be used as the latest version of the variable for phi-function
    # insertion. The "liveness", therefore, corresponds to the SSA version of the
    # variable determined by the index.
    phi_args: list[dict[str, int]] = []

    # BB-wise list of variables that are used in the BB (on RHS) along with
    # their first SSA versions in the BB, used to determine destinations for
    # phi-function insertion.
    phi_targets: list[dict[str, int]] = []

    basic_blocks: list[tuple[label, dict[str, basic_block]]] = []

    for i in range(len(basic_block_boundaries) - 1):
        bb = []
        for line, instr in enumerate(ir[basic_block_boundaries[i] : basic_block_boundaries[i + 1]]):
            bb.extend(to_statement(instr, i, basic_block_boundaries))
        print(f"L{i}:\n    " + "\n    ".join(str(stmt) for stmt in bb))

    # return [
    #     # Tuples of (node, node_attr_dict) for insertion into the graph.
    #     # node = label of the basic block, node_attr_dict = {'basic_block': basic_block(statements)}
    #     (label(i), {"basic_block": basic_block(
    #         # Convert IR statements to SSA statements for this basic block
    #         _ssa_bb_from_ir_bb(stmt, basic_block_boundaries, variables)
    #         for stmt in ir[basic_block_boundaries[i] : basic_block_boundaries[i + 1]]
    #     )})
    #     for i in range(len(basic_block_boundaries) - 1)
    # ]
    return basic_blocks

def ssa_cfg_from_ir(ir: list[tuple[ChironAST.Instruction, int]]) -> nx.DiGraph[label]:
    '''
    Construct a control flow graph (CFG) for the SSA form of the IR.
    The CFG is represented as a directed graph where the nodes are
    basic blocks and the edges represent control flow between the blocks.

    :param list[tuple[ChironAST.Instruction, int]] ir: The list of IR
        instructions to convert to SSA form and construct the CFG from.
    :return networkx.DiGraph[label]: The control flow graph as a directed
        graph.
    '''

    # Create basic blocks from the IR
    basic_blocks = _get_ssa_bbs(ir)

    del ir # Free memory used by the IR list

    cfg: nx.DiGraph[label] = nx.DiGraph()
    cfg.add_nodes_from(basic_blocks)

    return cfg