import sys

import networkx as nx
from ChironAST import ChironAST

from .basic_block import basic_block
from .label import label
from .renumber import renumber_variables
from .statements import (jump_statement, statement, syscall_statement,
                         φ_statement)
from .to_statement import to_statement


def _get_leaders(ir: list[tuple[ChironAST.Instruction, int]]) -> list[int]:
    '''
    Identify the indices in the IR where basic blocks start. A basic block
    starts at the first instruction, after a control flow instruction (like
    a jump or branch), or at the destination of a control flow instruction.

    :param list[ChironAST.Instruction] ir: The list of IR instructions to
        analyse.
    :return list[int]: A sorted list of indices where basic blocks start.
    '''

    boundaries = [0]  # The first instruction is always the start of a basic block

    for i, instr in enumerate(ir):
        if instr[1] != 1:
            # If the instruction is a jump/branch, add the target as a leader
            boundaries.append(i + instr[1])

            # Add the next instruction as a leader
            boundaries.append(i + 1)

            # NOTE: If the instruction is a jump/branch but its target is the
            # next instruction, the instruction is redundant and should be
            # removed at BB-level analysis, so we don't need to add the target
            # as a boundary in that case.
            #
            # If the instruction is an unconditional jump, the next instruction
            # may be unreachable. While we can detect this at BB-level analysis,
            # we use the next BB's start to find the current BB's end. Instead,
            # we will remove unreachable blocks at CFG-level analysis.

        elif isinstance(instr[0], (ChironAST.PenCommand, ChironAST.MoveCommand, ChironAST.GotoCommand)):
            # These are syscalls, which also cause control flow changes, so we
            # treat them as jumps (which is what they'll become later).
            boundaries.append(i + 1)

    return sorted(set(boundaries))

def _get_tac_bbs(ir: list[tuple[ChironAST.Instruction, int]], print_debug: bool = False) \
    -> list[tuple[label, dict[str, basic_block]]]:
    '''
    Create basic blocks from the IR based on the identified boundaries.

    :param list[tuple[ChironAST.Instruction, int]] ir:
        The list of IR instructions to convert to basic blocks.
    :return list[tuple[label, dict[str, basic_block]]]:
        A list of basic blocks created from the IR.
    '''

    # Locate basic block boundaries in the IR
    basic_block_boundaries = _get_leaders(ir)
    basic_block_boundaries.append(len(ir))  # Add the end of the IR as a boundary
    # Note that the past-the-end address may have been generated by _get_leaders()
    # if it was the target of a jump (the target being the end of the program).
    # Appending in this case causes a duplicate entry, which is alright: the
    # past-the-end address then falls into an empty basic block.

    version: dict[str, int] = {}            # Mapping of variable names to their current SSA version numbers

    # BB-wise list of variables that are used in the BB (on LHS) along with
    # their first SSA versions in the BB, used to determine destinations for
    # phi-function insertion.
    phi_args: list[dict[str, set[int]]] = []

    # BB-wise list of variables that are used in the BB (on RHS) along with
    # their first SSA versions in the BB, used to determine destinations for
    # phi-function insertion.
    phi_targets: list[dict[str, int]] = []

    basic_blocks: list[tuple[label, dict[str, basic_block]]] = []

    for i in range(len(basic_block_boundaries) - 1):
        bb = []
        for line, instr in enumerate(ir[basic_block_boundaries[i] : basic_block_boundaries[i + 1]]):
            bb.extend(to_statement(instr, i, basic_block_boundaries))
        if print_debug:
            print(f"L{i}:\n    " + "\n    ".join(str(stmt) for stmt in bb)) # Print tac statements for debugging
        basic_blocks.append((label(i), {"basic_block": basic_block(bb)}))

    #     seen_vars: set[str] = set() # Set of variable names seen so far in this BB

    #     # List of variables that are live at the end of the BB along with
    #     # their versions, used to determine sources for phi-function insertion in
    #     # successor BB.
    #     #
    #     # All variables are actually assumed alive at the end of the BB; the key
    #     # information here is to find the last assigned index for each variable in the
    #     # BB, which will be used as the latest version of the variable for phi-function
    #     # insertion. The "liveness", therefore, corresponds to the SSA version of the
    #     # variable determined by the index.
    #     next_phi_args: dict[str, int] = {}

    #     phi_targets.append({})

    #     for i in range(len(bb)):
    #         renumber_variables(bb[i], version, next_phi_args, phi_targets[i], seen_vars)

    #     # See NetworkX construction in :ssa_cfg_from_ir():.
    #     basic_blocks.append((label(i), {"basic_block": basic_block(bb)}))
    
    # for i in range(len(basic_blocks) - 1):
    #     # Add φ-statements for variables that are live at the end of the current BB and used in the next BB
    #     for var, version in phi_args[i].items():
    #         if var in phi_targets[i + 1]:
    #             bb = basic_blocks[i + 1][1]["basic_block"]
    #             bb.statements.insert(0, φ_statement(variable(var, version), [variable(var, version)]))
    #             print(f"Inserted φ-statement for variable {var} in BB {i + 1} with version {version}") # Debugging




















        

    # return [
    #     # Tuples of (node, node_attr_dict) for insertion into the graph.
    #     # node = label of the basic block, node_attr_dict = {'basic_block': basic_block(statements)}
    #     (label(i), {"basic_block": basic_block(
    #         # Convert IR statements to SSA statements for this basic block
    #         _ssa_bb_from_ir_bb(stmt, basic_block_boundaries, variables)
    #         for stmt in ir[basic_block_boundaries[i] : basic_block_boundaries[i + 1]]
    #     )})
    #     for i in range(len(basic_block_boundaries) - 1)
    # ]
    return basic_blocks

def tac_cfg_from_ir(ir: list[tuple[ChironAST.Instruction, int]], print_debug: bool = False) -> nx.DiGraph[label]:
    '''
    Construct a control flow graph (CFG) for the three-address code form of the IR.
    The CFG is represented as a directed graph where the nodes are
    basic blocks and the edges represent control flow between the blocks.

    :param list[tuple[ChironAST.Instruction, int]] ir: The list of IR
        instructions to convert to SSA form and construct the CFG from.
    :return networkx.DiGraph[label]: The control flow graph as a directed
        graph.
    '''

    # Create basic blocks from the IR
    basic_blocks = _get_tac_bbs(ir, print_debug)

    del ir # Free memory used by the IR list

    cfg: nx.DiGraph[label] = nx.DiGraph()
    cfg.add_nodes_from(basic_blocks)
    for i in range(len(basic_blocks) - 1):
        bb = basic_blocks[i][1]["basic_block"].instructions
        if not bb:
            continue
        last_stmt = bb[-1]
        if isinstance(last_stmt, jump_statement):
            if last_stmt.is_conditional:
                cfg.add_edge(label(i), label(last_stmt.target1)) # Fall-through edge
                cfg.add_edge(label(i), label(last_stmt.target2)) # Jump edge
            else:
                cfg.add_edge(label(i), label(last_stmt.target))  # Jump edge
        else:
            cfg.add_edge(label(i), label(i + 1))

    return cfg